### ISSUE TITLE
Chapter 7

### ISSUE THREAD

**Issue by davidbp** [PacktPublishing/Julia-1.x-By-Example#2]
Hi Adrian,

Some problems in the chapter.
Please close the issue once they are solved and tell me what's been done.

#### Dataframes versions and casting

Using
```julia
### Dataframes version:	0.10.1
path_to_ratings  = "../chapter7_data/ratings.dat.txt"
ratings = CSV.read(path_to_ratings, header = false);

UserID | ProfileID | Rating
-- | -- | --
Nullable{Int64}(1) | Nullable{Int64}(133) | Nullable{Int64}(8)
Nullable{Int64}(1) | Nullable{Int64}(720) | Nullable{Int64}(6)
```

If I cast it manually then it works

```julia
ratings[:UserID] = Array{Int}(ratings[:UserID])
ratings[:ProfileID] = Array{Int}(ratings[:ProfileID])
ratings[:Rating] = Array{Int}(ratings[:Rating])
head(ratings, 3)

UserID | ProfileID | Rating
-- | -- | --
1 | 133 | 8
1 | 720 | 6
1 | 971 | 10
```

#### results differ

Training and train-test partitions need seeds to make results reproducible

```intersect(test_profile_ids, recommendations_to_profiles(recommend(recommender, 1, 100, [1:profile_counter...])))
0-element Array{Int64,1}
```

```
intersect(test_profile_ids, recommendations_to_profiles(recommend(recommender, 100, 100, [1:profile_counter...])))
0-element Array{Int64,1}
```

**Comment by essenciary** [comment]
Hi David, 

It should be `DataFrames` 0.11 - we can pretty much give up on `DataFrames` 0.10, it's been superseded.

I need to go over the initial chapters and update everything for `DataFrames` 0.11. `DataFrames` 0.11 no longer uses `Nullables` but `Missings`. 

Can you please swap to `DataFrames` 0.11?

**Comment by davidbp** [comment]
I have updated the DataFrames package but it updates to 0.10.1.
I have also removed it and installed it again and it's not working.

Probably it's worth waiting a bit to get this "automatically managed" by `Pkg.add`.
I guess Julia 0.7 will have this working properly.
 
```
julia> Pkg.rm("DataFrames")
INFO: Removing DataFrames (unregistered)

julia> Pkg.add("DataFrames") 
INFO: Installing DataFrames v0.10.1
INFO: Building SpecialFunctions
INFO: Package database updated
```

**Comment by techsachinkumar** [comment]
Hi @davidbp 

It seems @essenciary has made the changes and updated in the code files.
You may check and give an update. You may reopen in case any problem.

Closed.
