### ISSUE TITLE
Chapter 3 - run webcrawler.jl

### ISSUE THREAD

**Issue by leonistor** [PacktPublishing/Julia-1.x-By-Example#3]
On page 144, running webcrawler.jl as instructed `julia webcrawler.jl` will fail to load the required packages (HTTP, Gumbo). Got it working with `julia --project=@. webcrawler.jl`.

Running julia version 1.0.3 on Ubuntu 18.04.
Excellent book, btw, thank you, Adrian!

**Comment by essenciary** [comment]
@leonistor Thanks for reporting this. Can you please detail your workflow, prior to the error? Did you download the `Project` and `Manifest` files and used `pkg> instantiate`?

I'm glad that you're enjoying the book, thanks for the kind words, much appreciated!

**Comment by leonistor** [comment]
My mistake: I haven't paid attention to "in the folder where the file is stored" in the previous paragraph and, while using Juno, got confused. Please mark this issue as "not a bug". Thank you!
