### ISSUE TITLE
Chapter 5, `HTTP.Server` not defined with v0.8.0

### ISSUE THREAD

**Issue by kota7** [PacktPublishing/Julia-1.x-By-Example#4]
The sample `hello.jl` in Chapter 5 no longer works with `HTTP@v0.8.0`, gets

```
UndefVarError: Server not defined
```

Downgrading to `v0.7.1` works, so perhaps there has been API change in the package.  

This is not a book issue and I can work with the older version during learning this book, but can someone possibly suggest a quick fix with new version for future reference?

**Comment by kota7** [comment]
I find the following works with `v0.8.0`.

Changes are:
* `HTTP.serve` takes `router` directly, instead of `Server(router)`.
* `HTTP.register` is deprecated, `HTTP.@register` is recommended.
* `HTTP.HandlerFunction` is now `HTTP.RequestHandlerFunction`.

```julia
using HTTP, Sockets

const HOST = ip"0.0.0.0"
const PORT = 9999
router = HTTP.Router()

HTTP.@register(router, "GET", "/", HTTP.RequestHandlerFunction(
  req -> HTTP.Messages.Response(200, "Hello World!")))
HTTP.@register(router, "GET", "/bye", HTTP.RequestHandlerFunction(
  req -> HTTP.Messages.Response(200, "Bye")))
HTTP.@register(router, "GET", "*", HTTP.RequestHandlerFunction(
  req -> HTTP.Messages.Response(404, "Not found")))
HTTP.serve(router, HOST, PORT)
```

**Comment by essenciary** [comment]
Thanks @kota7 for reporting this. 
Indeed, `HTTP` 0.8 introduces breaking changes. Let me check with the team, see if there's any way to update this.

**Comment by githubce** [comment]
Hi @essenciary 

You can directly update the codes on GitHub as per the new update.

Regards,
